name: note2md
description: A Dart CLI tool for exporting articles of note.com.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.1.0
  html: ^0.15.0
  http: ^0.13.3
  puppeteer: ^2.0.0

dev_dependencies:
  test: ^1.17.3